#!/usr/bin/env python

import sys
import signal
import os
import time
import subprocess as sb

try:
    RESOLUTION=sys.argv[1]
except:
    RESOLUTION='320x200'
XX=320
YY=200
try:
    x, y = [int(x) for x in RESOLUTION.split('x')]
    xf = int(x / XX)
    yf = int(y / YY)
    fac = min(xf, yf)
    fac = max(fac, 1)
    fac = min(fac, 4)
except:
    print("RESOLUTION must be in <num>x<num> format")
    sys.exit(1)

print('Using factor', fac)

c = ["Xephyr", "-screen", str(x) + 'x' + str(y) + "x8", ":12"]
xephyr = sb.Popen(c).pid

time.sleep(1)

try:
    DOOM="cd %s/cmake-build-debug && DISPLAY=:12 ./DOOM %s" % (os.path.dirname(os.path.realpath(__file__)), '-' + str(fac))
    print(DOOM)
    os.system(DOOM)
finally:
    os.kill(xephyr, signal.SIGTERM)

