#!/usr/bin/env python

import sys
import signal
import os
import time
import subprocess as sb

SCALE=''

DISPLAY='eDP1'
RESOLUTION='1366x768'

c = ["Xephyr", "-screen", RESOLUTION + "x8", ":12"]
xephyr = sb.Popen(c).pid

time.sleep(3)

try:
    DOOM="cd %s/cmake-build-debug && DISPLAY=:12 ./DOOM %s" % (os.path.dirname(os.path.realpath(__file__)), ''.join(sys.argv[1:]))
    os.system(DOOM)
finally:
    os.kill(xephyr, signal.SIGTERM)

