#!/usr/bin/env python

import sys
import os
import time

SCALE=''
DISPLAY=''

try:
    SCALE=int(sys.argv[1])
except:
    SCALE=2
try:
    DISPLAY=sys.argv[2]
except:
    DISPLAY='eDP1'

print(__file__)

scaler = 1.0/SCALE

c = "Xephyr -screen 320x200x8 :12 &"
os.system(c)

time.sleep(3)

try:
    os.system("xrandr --output %s --scale %sx%s" % (DISPLAY, scaler, scaler))
    DOOM="cd %s/cmake-build-debug && DISPLAY=:12  ./DOOM" % os.path.dirname(os.path.realpath(__file__))
    os.system(DOOM)
finally:
    os.system("xrandr --output %s --scale 1x1" % DISPLAY)
    os.system("pkill -9 Xephyr")

